name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        include:
        - operating-system: ubuntu-latest
        - operating-system: windows-latest
    steps:
    - uses: actions/checkout@v3
    - run: .github/download-dependencies.sh
    - name: Install Lazarus
      uses: gcarreno/setup-lazarus@v3.0.16
      with:
        lazarus-version: stable
    - name: Ubuntu
      if: ${{ matrix.operating-system == 'ubuntu-latest' }}
      uses: ./.github/workflows/ubuntu.yml
    - name: Windows
      if: ${{ matrix.operating-system == 'windows-latest' }}
      uses: ./.github/workflows/windows.yml
