name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Lazarus
      uses: gcarreno/setup-lazarus@v3.0.16
      with:
        lazarus-version: stable
    - run: .github/download-dependencies.sh && .github/setup-fpc-cfg.sh 
    - run: lazbuild --add-package internettools/internettools.lpk
    - run: ./manage.sh linux64
    - name: Test Xidel
      run: ./tests/tests.sh
    - name: 'Upload '
      uses: actions/upload-artifact@v3
      with:
        name: xidel.linux64.tar.gz
        path: xidel*.tar.gz
    - name: 'Upload '
      uses: actions/upload-artifact@v3
      with:
        name: xidel.linux64.deb
        path: xidel*.deb


  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Lazarus
      uses: gcarreno/setup-lazarus@v3.0.16
      with:
        lazarus-version: stable
    - run: . .github/download-dependencies.sh && . .github/setup-fpc-cfg.sh 
    - run: lazbuild --add-package internettools/internettools.lpk
    - run: ./manage.sh win64
    - name: Test Xidel 64
      run: ./tests/tests.sh
    - name: 'Upload '
      uses: actions/upload-artifact@v3
      with:
        name: xidel.win64.zip
        path: xidel*.zip
    - run: ./manage.sh win32
    - name: Test Xidel 32
      run: ./tests/tests.sh
